[2024-03-30T00:32:50.053+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:32:50.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:32:50.061+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:32:50.060+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:32:50.111+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:32:50.109+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 3, in <module>
    from heighliner.utils import load_yaml
ModuleNotFoundError: No module named 'heighliner'
[2024-03-30T00:32:50.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:32:50.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.184 seconds
[2024-03-30T00:33:20.430+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:33:20.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:33:20.439+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:33:20.438+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:33:20.468+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:33:20.463+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 3, in <module>
    from heighliner.utils import load_yaml
ModuleNotFoundError: No module named 'heighliner'
[2024-03-30T00:33:20.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:33:20.521+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.094 seconds
[2024-03-30T00:33:50.623+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:33:50.624+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:33:50.640+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:33:50.640+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:33:50.657+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:33:50.655+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 3, in <module>
    from heighliner.utils import load_yaml
ModuleNotFoundError: No module named 'heighliner'
[2024-03-30T00:33:50.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:33:50.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.065 seconds
[2024-03-30T00:34:07.782+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:34:07.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:34:07.785+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:34:07.785+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:34:07.805+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:34:07.802+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 3, in <module>
    from heighliner.utils import load_yaml
ModuleNotFoundError: No module named 'heighliner'
[2024-03-30T00:34:07.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:34:07.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.045 seconds
[2024-03-30T00:34:37.959+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:34:37.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:34:37.961+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:34:37.961+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:34:37.976+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:34:37.973+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 3, in <module>
    from heighliner.utils import load_yaml
ModuleNotFoundError: No module named 'heighliner'
[2024-03-30T00:34:37.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:34:38.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.048 seconds
[2024-03-30T00:35:08.180+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:35:08.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:35:08.185+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:35:08.185+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:35:08.199+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:35:08.196+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 3, in <module>
    from heighliner.utils import load_yaml
ModuleNotFoundError: No module named 'heighliner'
[2024-03-30T00:35:08.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:35:08.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.059 seconds
[2024-03-30T00:35:38.372+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:35:38.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:35:38.376+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:35:38.375+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:35:38.389+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:35:38.386+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 3, in <module>
    from heighliner.utils import load_yaml
ModuleNotFoundError: No module named 'heighliner'
[2024-03-30T00:35:38.390+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:35:38.411+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.042 seconds
[2024-03-30T00:40:40.352+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:40:40.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:40:40.358+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:40:40.358+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:40:40.456+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:40:40.454+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 11, in build_dags
    dag_id = dag_definition["dag_id"]
KeyError: 'dag_id'
[2024-03-30T00:40:40.457+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:40:40.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.129 seconds
[2024-03-30T00:41:10.533+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:41:10.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:41:10.535+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:41:10.535+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:41:10.598+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:41:10.596+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 11, in build_dags
    dag_id = dag_definition["dag_id"]
KeyError: 'dag_id'
[2024-03-30T00:41:10.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:41:10.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.090 seconds
[2024-03-30T00:44:06.970+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:44:06.971+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:44:06.973+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:44:06.973+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:44:07.040+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:44:07.036+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 11, in build_dags
    dag_id = dag_definition["job_name"]
KeyError: 'job_name'
[2024-03-30T00:44:07.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:44:07.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.097 seconds
[2024-03-30T00:44:37.161+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:44:37.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:44:37.169+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:44:37.169+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:44:37.431+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:44:37.428+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 11, in build_dags
    dag_id = dag_definition["job_name"]
KeyError: 'job_name'
[2024-03-30T00:44:37.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:44:37.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.340 seconds
[2024-03-30T00:53:30.986+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:53:30.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:53:30.995+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:53:30.994+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:53:31.140+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:53:31.137+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 11, in build_dags
    dag_id = dag_definition["job_name"]
KeyError: 'job_name'
[2024-03-30T00:53:31.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:53:31.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.188 seconds
[2024-03-30T00:54:01.208+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:54:01.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:54:01.210+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:54:01.210+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:54:01.302+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:54:01.300+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 11, in build_dags
    dag_id = dag_definition["job_name"]
KeyError: 'job_name'
[2024-03-30T00:54:01.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:54:01.320+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.116 seconds
[2024-03-30T00:54:31.476+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:54:31.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:54:31.479+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:54:31.479+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:54:31.949+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:54:31.948+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 11, in build_dags
    dag_id = dag_definition["job_name"]
KeyError: 'job_name'
[2024-03-30T00:54:31.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:54:31.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.490 seconds
[2024-03-30T00:56:07.731+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:56:07.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:56:07.736+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:56:07.735+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:56:07.821+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:56:07.818+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 14, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 123, in build
    self.load_values()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 114, in load_values
    self.job_name: str = self.job_info.get("job_name")
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "EmrAddStepsDAG" object has no field "job_name"
[2024-03-30T00:56:07.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:56:09.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 1.434 seconds
[2024-03-30T00:56:40.136+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:56:40.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:56:40.142+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:56:40.142+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:56:40.335+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:56:40.330+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 14, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 123, in build
    self.load_values()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 114, in load_values
    self.job_name: str = self.job_info.get("job_name")
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "EmrAddStepsDAG" object has no field "job_name"
[2024-03-30T00:56:40.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:56:40.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.259 seconds
[2024-03-30T00:57:10.584+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:57:10.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:57:10.597+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:57:10.596+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:57:10.706+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:57:10.703+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 14, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 123, in build
    self.load_values()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 114, in load_values
    self.job_name: str = self.job_info.get("job_name")
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "EmrAddStepsDAG" object has no field "job_name"
[2024-03-30T00:57:10.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:57:10.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.152 seconds
[2024-03-30T00:57:40.888+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:57:40.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:57:40.892+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:57:40.891+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:57:40.956+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:57:40.954+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 14, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 123, in build
    self.load_values()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 114, in load_values
    self.job_name: str = self.job_info.get("job_name")
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "EmrAddStepsDAG" object has no field "job_name"
[2024-03-30T00:57:40.957+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:57:40.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.089 seconds
[2024-03-30T00:58:11.050+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:58:11.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:58:11.053+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:58:11.053+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:58:11.124+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:58:11.122+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 14, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 123, in build
    self.load_values()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 114, in load_values
    self.job_name: str = self.job_info.get("job_name")
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "EmrAddStepsDAG" object has no field "job_name"
[2024-03-30T00:58:11.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:58:11.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.101 seconds
[2024-03-30T00:58:41.322+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:58:41.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:58:41.325+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:58:41.324+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:58:41.394+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:58:41.391+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 14, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 123, in build
    self.load_values()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 114, in load_values
    self.job_name: str = self.job_info.get("job_name")
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "EmrAddStepsDAG" object has no field "job_name"
[2024-03-30T00:58:41.394+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:58:41.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.099 seconds
[2024-03-30T00:59:11.490+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:59:11.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:59:11.493+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:59:11.493+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:59:11.567+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:59:11.565+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 14, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 123, in build
    self.load_values()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 114, in load_values
    self.job_name: str = self.job_info.get("job_name")
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "EmrAddStepsDAG" object has no field "job_name"
[2024-03-30T00:59:11.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:59:11.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.098 seconds
[2024-03-30T00:59:41.695+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T00:59:41.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T00:59:41.698+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:59:41.697+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T00:59:41.773+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:59:41.771+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 14, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 123, in build
    self.load_values()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 114, in load_values
    self.job_name: str = self.job_info.get("job_name")
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "EmrAddStepsDAG" object has no field "job_name"
[2024-03-30T00:59:41.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T00:59:41.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.106 seconds
[2024-03-30T01:00:11.969+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:00:11.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:00:11.971+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:00:11.971+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:00:12.034+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:00:12.032+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 14, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 123, in build
    self.load_values()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 114, in load_values
    self.job_name: str = self.job_info.get("job_name")
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "EmrAddStepsDAG" object has no field "job_name"
[2024-03-30T01:00:12.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:00:12.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.090 seconds
[2024-03-30T01:02:07.426+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:02:07.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:02:07.430+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:07.429+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:02:07.848+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py:437 RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
[2024-03-30T01:02:07.865+0000] {processor.py:840} INFO - DAG(s) 'dag_create_emr_cluster', 'dag_autoserv_001', 'dag_autoserv_002' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:02:08.073+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.072+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:dag_create_emr_cluster
[2024-03-30T01:02:08.104+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.104+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:dag_create_emr_cluster
[2024-03-30T01:02:08.113+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.112+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:dag_create_emr_cluster
[2024-03-30T01:02:08.127+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.127+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:dag_autoserv_001
[2024-03-30T01:02:08.133+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.133+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:dag_autoserv_001
[2024-03-30T01:02:08.139+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.139+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:dag_autoserv_001
[2024-03-30T01:02:08.157+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.157+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:dag_autoserv_002
[2024-03-30T01:02:08.169+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.169+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:dag_autoserv_002
[2024-03-30T01:02:08.182+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.181+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:dag_autoserv_002
[2024-03-30T01:02:08.182+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.182+0000] {dag.py:3047} INFO - Sync 3 DAGs
[2024-03-30T01:02:08.195+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.194+0000] {dag.py:3069} INFO - Creating ORM DAG for dag_autoserv_002
[2024-03-30T01:02:08.196+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.195+0000] {dag.py:3069} INFO - Creating ORM DAG for dag_autoserv_001
[2024-03-30T01:02:08.196+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.196+0000] {dag.py:3069} INFO - Creating ORM DAG for dag_create_emr_cluster
[2024-03-30T01:02:08.206+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.206+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_autoserv_001 to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:02:08.207+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.207+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_autoserv_002 to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:02:08.208+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:08.208+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_create_emr_cluster to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:02:08.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.812 seconds
[2024-03-30T01:02:38.763+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:02:38.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:02:38.769+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:38.769+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:02:39.544+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py:437 RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
[2024-03-30T01:02:39.607+0000] {processor.py:840} INFO - DAG(s) 'dag_create_emr_cluster', 'dag_autoserv_002', 'dag_autoserv_001' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:02:39.657+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:39.657+0000] {dag.py:3047} INFO - Sync 3 DAGs
[2024-03-30T01:02:40.088+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:40.088+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_autoserv_001 to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:02:40.099+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:40.099+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_autoserv_002 to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:02:40.101+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:02:40.101+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_create_emr_cluster to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:02:40.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 1.416 seconds
[2024-03-30T01:03:10.355+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:03:10.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:03:10.360+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:03:10.360+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:03:10.590+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py:437 RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
[2024-03-30T01:03:10.603+0000] {processor.py:840} INFO - DAG(s) 'dag_autoserv_001', 'dag_autoserv_002', 'dag_create_emr_cluster' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:03:10.638+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:03:10.637+0000] {dag.py:3047} INFO - Sync 3 DAGs
[2024-03-30T01:03:10.677+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:03:10.676+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_autoserv_001 to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:03:10.680+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:03:10.679+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_autoserv_002 to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:03:10.681+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:03:10.681+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_create_emr_cluster to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:03:10.711+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.359 seconds
[2024-03-30T01:03:40.875+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:03:40.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:03:40.881+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:03:40.881+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:03:41.074+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py:437 RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
[2024-03-30T01:03:41.082+0000] {processor.py:840} INFO - DAG(s) 'dag_create_emr_cluster', 'dag_autoserv_001', 'dag_autoserv_002' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:03:41.111+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:03:41.111+0000] {dag.py:3047} INFO - Sync 3 DAGs
[2024-03-30T01:03:41.130+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:03:41.130+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_autoserv_001 to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:03:41.134+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:03:41.134+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_autoserv_002 to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:03:41.136+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:03:41.136+0000] {dag.py:3834} INFO - Setting next_dagrun for dag_create_emr_cluster to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:03:41.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.281 seconds
[2024-03-30T01:16:55.154+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:16:55.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:16:55.157+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:16:55.157+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:16:55.633+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:16:55.629+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 58, in build
    jobs = registry.get(self.module_name).get("jobs")
AttributeError: 'NoneType' object has no attribute 'get'
[2024-03-30T01:16:55.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:16:55.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.501 seconds
[2024-03-30T01:17:25.955+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:17:25.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:17:25.961+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:17:25.960+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:17:26.740+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:17:26.732+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 58, in build
    jobs = registry.get(self.module_name).get("jobs")
AttributeError: 'NoneType' object has no attribute 'get'
[2024-03-30T01:17:26.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:17:26.790+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.838 seconds
[2024-03-30T01:17:56.983+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:17:56.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:17:56.986+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:17:56.985+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:17:57.194+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:17:57.191+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 58, in build
    jobs = registry.get(self.module_name).get("jobs")
AttributeError: 'NoneType' object has no attribute 'get'
[2024-03-30T01:17:57.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:17:57.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.231 seconds
[2024-03-30T01:18:27.359+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:18:27.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:18:27.361+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:18:27.361+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:18:27.541+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:18:27.538+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 58, in build
    jobs = registry.get(self.module_name).get("jobs")
AttributeError: 'NoneType' object has no attribute 'get'
[2024-03-30T01:18:27.542+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:18:27.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.201 seconds
[2024-03-30T01:32:27.179+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:32:27.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:32:27.182+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:32:27.182+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:32:27.656+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:32:27.654+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 95, in build
    TriggerDagRunOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
TypeError: __init__() missing 1 required positional argument: 'task_id'
[2024-03-30T01:32:27.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:32:27.673+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.497 seconds
[2024-03-30T01:32:57.950+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:32:57.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:32:57.956+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:32:57.955+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:32:58.426+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:32:58.417+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 95, in build
    TriggerDagRunOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
TypeError: __init__() missing 1 required positional argument: 'task_id'
[2024-03-30T01:32:58.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:32:58.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.513 seconds
[2024-03-30T01:33:28.525+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:33:28.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:33:28.533+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:33:28.533+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:33:28.789+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:33:28.785+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 95, in build
    TriggerDagRunOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
TypeError: __init__() missing 1 required positional argument: 'task_id'
[2024-03-30T01:33:28.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:33:28.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.302 seconds
[2024-03-30T01:39:58.230+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:39:58.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:39:58.256+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:39:58.255+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:40:00.144+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:40:00.621+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:40:00.620+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:autoserv_EMR_MODULE_BUS
[2024-03-30T01:40:00.643+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:40:00.642+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:autoserv_EMR_MODULE_BUS
[2024-03-30T01:40:00.657+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:40:00.656+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:autoserv_EMR_MODULE_BUS
[2024-03-30T01:40:00.658+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:40:00.658+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T01:40:00.688+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:40:00.688+0000] {dag.py:3069} INFO - Creating ORM DAG for autoserv_EMR_MODULE_BUS
[2024-03-30T01:40:00.717+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:40:00.717+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:40:00.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 2.592 seconds
[2024-03-30T01:40:31.066+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:40:31.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:40:31.083+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:40:31.082+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:40:32.732+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:40:32.801+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:40:32.800+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T01:40:33.275+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:40:33.275+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:40:33.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 2.303 seconds
[2024-03-30T01:41:03.628+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:41:03.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:41:03.658+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:41:03.657+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:41:04.462+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:41:04.825+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:41:04.824+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T01:41:05.078+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:41:05.078+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:41:05.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 1.716 seconds
[2024-03-30T01:41:35.442+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:41:35.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:41:35.446+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:41:35.446+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:41:35.636+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:41:35.664+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:41:35.664+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T01:41:35.683+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:41:35.683+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:41:35.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.264 seconds
[2024-03-30T01:42:05.860+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:42:05.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:42:05.863+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:42:05.862+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:42:06.005+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:42:06.030+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:42:06.030+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T01:42:06.046+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:42:06.045+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:42:06.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.201 seconds
[2024-03-30T01:42:36.087+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:42:36.088+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:42:36.089+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:42:36.089+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:42:36.237+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:42:36.252+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:42:36.252+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T01:42:36.268+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:42:36.267+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:42:36.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.204 seconds
[2024-03-30T01:43:06.448+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:43:06.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:43:06.450+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:43:06.450+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:43:06.599+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:43:06.616+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:43:06.616+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T01:43:06.631+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:43:06.630+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:43:06.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.207 seconds
[2024-03-30T01:43:36.816+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:43:36.817+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:43:36.818+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:43:36.818+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:43:36.979+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:43:37.000+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:43:36.999+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T01:43:37.018+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:43:37.018+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T01:43:37.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.219 seconds
[2024-03-30T01:49:09.391+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:49:09.392+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:49:09.394+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:49:09.394+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:49:10.007+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:49:10.004+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:49:10.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:49:10.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.779 seconds
[2024-03-30T01:49:40.538+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:49:40.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:49:40.548+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:49:40.547+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:49:41.740+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:49:41.723+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:49:41.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:49:41.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 1.287 seconds
[2024-03-30T01:50:11.861+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:50:11.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:50:11.864+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:50:11.864+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:50:12.065+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:50:12.062+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:50:12.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:50:12.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.228 seconds
[2024-03-30T01:50:42.120+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:50:42.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:50:42.122+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:50:42.122+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:50:42.305+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:50:42.303+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:50:42.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:50:42.320+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.203 seconds
[2024-03-30T01:51:12.379+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:51:12.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:51:12.381+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:51:12.381+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:51:12.558+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:51:12.555+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:51:12.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:51:12.571+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.194 seconds
[2024-03-30T01:51:42.644+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:51:42.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:51:42.646+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:51:42.645+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:51:42.835+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:51:42.833+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:51:42.835+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:51:42.848+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.207 seconds
[2024-03-30T01:52:12.933+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:52:12.934+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:52:12.935+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:52:12.935+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:52:13.109+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:52:13.107+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:52:13.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:52:13.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.196 seconds
[2024-03-30T01:52:43.183+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:52:43.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:52:43.185+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:52:43.185+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:52:43.343+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:52:43.340+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:52:43.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:52:43.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.186 seconds
[2024-03-30T01:53:13.491+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:53:13.492+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:53:13.493+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:53:13.493+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:53:13.700+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:53:13.697+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:53:13.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:53:13.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.246 seconds
[2024-03-30T01:53:43.931+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:53:43.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:53:43.933+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:53:43.933+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:53:44.097+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:53:44.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:53:44.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:53:44.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.185 seconds
[2024-03-30T01:54:14.156+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:54:14.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:54:14.158+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:54:14.158+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:54:14.339+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:54:14.336+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:54:14.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:54:14.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.202 seconds
[2024-03-30T01:54:44.419+0000] {processor.py:161} INFO - Started process (PID=116) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:54:44.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:54:44.420+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:54:44.420+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:54:44.582+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:54:44.579+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:54:44.583+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:54:44.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.180 seconds
[2024-03-30T01:55:14.667+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:55:14.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:55:14.668+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:55:14.668+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:55:14.823+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:55:14.819+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:55:14.823+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:55:14.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.181 seconds
[2024-03-30T01:55:44.924+0000] {processor.py:161} INFO - Started process (PID=130) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:55:44.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:55:44.926+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:55:44.926+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:55:45.087+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:55:45.085+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:55:45.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:55:45.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.179 seconds
[2024-03-30T01:56:15.239+0000] {processor.py:161} INFO - Started process (PID=137) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:56:15.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:56:15.240+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:56:15.240+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:56:15.413+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:56:15.410+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:56:15.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:56:15.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.201 seconds
[2024-03-30T01:56:45.610+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:56:45.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:56:45.612+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:56:45.612+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:56:45.781+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:56:45.779+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:56:45.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:56:45.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.199 seconds
[2024-03-30T01:57:15.958+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:57:15.959+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:57:15.959+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:57:15.959+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:57:16.151+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:57:16.148+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:57:16.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:57:16.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.215 seconds
[2024-03-30T01:57:46.326+0000] {processor.py:161} INFO - Started process (PID=158) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:57:46.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:57:46.328+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:57:46.328+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:57:46.480+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:57:46.477+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:57:46.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:57:46.501+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.178 seconds
[2024-03-30T01:58:16.673+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:58:16.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:58:16.676+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:58:16.675+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:58:16.823+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:58:16.821+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:58:16.824+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:58:16.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.176 seconds
[2024-03-30T01:58:46.990+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:58:46.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:58:46.992+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:58:46.992+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:58:47.155+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:58:47.153+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:58:47.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:58:47.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.192 seconds
[2024-03-30T01:59:17.354+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:59:17.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:59:17.356+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:59:17.356+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:59:17.495+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:59:17.494+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:59:17.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:59:17.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.156 seconds
[2024-03-30T01:59:47.657+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T01:59:47.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T01:59:47.658+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:59:47.658+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T01:59:47.802+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:59:47.800+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 36, in build_dags
    self.build_emr_create_cluster_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/builder.py", line 33, in build_emr_create_cluster_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/heighliner/models.py", line 66, in build
    module_subdags_ids.remove(self.dag_id)
ValueError: list.remove(x): x not in list
[2024-03-30T01:59:47.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T01:59:47.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.172 seconds
[2024-03-30T02:04:27.511+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T02:04:27.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T02:04:27.515+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:04:27.514+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T02:04:28.179+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T02:04:28.417+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:04:28.416+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T02:04:28.535+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:04:28.535+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T02:04:28.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 1.175 seconds
[2024-03-30T02:04:58.823+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T02:04:58.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T02:04:58.830+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:04:58.828+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T02:04:59.310+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T02:04:59.359+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:04:59.359+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T02:04:59.716+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:04:59.716+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T02:04:59.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.950 seconds
[2024-03-30T02:05:29.993+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T02:05:29.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T02:05:30.018+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:05:30.017+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T02:05:30.748+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T02:05:30.817+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:05:30.816+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T02:05:30.916+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:05:30.916+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T02:05:30.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.987 seconds
[2024-03-30T02:06:01.114+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T02:06:01.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T02:06:01.118+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:06:01.118+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T02:06:01.346+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T02:06:01.368+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:06:01.368+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T02:06:01.391+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:06:01.391+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T02:06:01.412+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.301 seconds
[2024-03-30T02:06:31.591+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T02:06:31.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T02:06:31.594+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:06:31.594+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T02:06:31.821+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T02:06:31.846+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:06:31.846+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T02:06:31.872+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:06:31.871+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T02:06:31.893+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.306 seconds
[2024-03-30T02:07:02.058+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T02:07:02.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T02:07:02.061+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:07:02.061+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T02:07:02.247+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T02:07:02.266+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:07:02.266+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T02:07:02.285+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:07:02.284+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T02:07:02.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.246 seconds
[2024-03-30T02:07:32.504+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T02:07:32.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T02:07:32.506+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:07:32.506+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T02:07:32.654+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T02:07:32.682+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:07:32.681+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T02:07:32.699+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:07:32.698+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T02:07:32.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.215 seconds
[2024-03-30T02:08:02.897+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/build_dags.py
[2024-03-30T02:08:02.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-30T02:08:02.899+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:08:02.899+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-30T02:08:03.060+0000] {processor.py:840} INFO - DAG(s) 'autoserv_EMR_MODULE_BUS' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-30T02:08:03.075+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:08:03.075+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-30T02:08:03.090+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:08:03.089+0000] {dag.py:3834} INFO - Setting next_dagrun for autoserv_EMR_MODULE_BUS to 2024-03-29 00:00:00+00:00, run_after=2024-03-30 00:00:00+00:00
[2024-03-30T02:08:03.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.220 seconds
